### ISSUE TITLE
循环依赖 bug

### ISSUE THREAD

**Issue by zhongyingxiang** [Snailclimb/jsoncat#15]
1.  没有逐层注入依赖，如图所示注入的依赖中的属性为 null
![image](https://user-images.githubusercontent.com/24939018/96552188-01636000-12e6-11eb-9349-c76452faf2f9.png)

**Comment by Snailclimb** [comment]
这里的原因应该是：这个方法本身是没有返回值，但是框架把其当成了有返回值类型的方法来执行导致了空指针异常。然后就导致了你现在的问题。

具体对应的代码是：`GetRequestHandler.java` 的下面这段代码：
![image](https://user-images.githubusercontent.com/29880145/96569226-768d6000-12fb-11eb-87f6-bcd25fbaf077.png)

**Comment by Snailclimb** [comment]
> 1. 没有逐层注入依赖，如图所示注入的依赖中的属性为 null
>    ![image](https://user-images.githubusercontent.com/24939018/96552188-01636000-12e6-11eb-9349-c76452faf2f9.png)

等下会简单修复一下这个问题。

**Comment by Snailclimb** [comment]
> 1. 没有逐层注入依赖，如图所示注入的依赖中的属性为 null
>    ![image](https://user-images.githubusercontent.com/24939018/96552188-01636000-12e6-11eb-9349-c76452faf2f9.png)

已经修复了这个问题：https://github.com/Snailclimb/jsoncat/commit/480176a8f179ece06caab84a95d0b5875231f43e

**Comment by zhongyingxiang** [comment]
看着还没解决
![image](https://user-images.githubusercontent.com/24939018/96593693-5fab3580-131c-11eb-9d94-3750b2372552.png)

**Comment by Snailclimb** [comment]
> 看着还没解决
> ![image](https://user-images.githubusercontent.com/24939018/96593693-5fab3580-131c-11eb-9d94-3750b2372552.png)

拉下最新的代码，你先把所有测试跑一下。。
