### ISSUE TITLE
依赖注入错误

### ISSUE THREAD

**Issue by lov3r** [Snailclimb/jsoncat#17]
**演示说明**
A和B都依赖C，然后C依赖与D，其实没有循环依赖问题，演示结果说明依赖注入不正确！

**演示结果**
![image](https://user-images.githubusercontent.com/33676682/96962763-0a4c6f80-153a-11eb-910c-46ad78fc4563.png)

**问题分析**
·
![image](https://user-images.githubusercontent.com/33676682/96963147-ba21dd00-153a-11eb-9003-6679cd4ad3f6.png)

**Comment by Snailclimb** [comment]
> **演示说明**
> A和B都依赖C，然后C依赖与D，其实没有循环依赖问题，演示结果说明依赖注入不正确！
> 
> **演示结果**
> ![image](https://user-images.githubusercontent.com/33676682/96962763-0a4c6f80-153a-11eb-910c-46ad78fc4563.png)
> 
> **问题分析**
> ·
> ![image](https://user-images.githubusercontent.com/33676682/96963147-ba21dd00-153a-11eb-9003-6679cd4ad3f6.png)

感谢，这部分写的时候没注意到。刚提交了一个commit修复：https://github.com/Snailclimb/jsoncat/commit/00ab3b2fad23446417b4a7af91381f2e1e8cc1b2
