### ISSUE TITLE
代码里一句注解也没有，看的稍微有点痛苦

### ISSUE THREAD

**Issue by ctywzy** [Snailclimb/jsoncat#20]

**Comment by audio-github-2020** [comment]
> _No description provided._

找到这行代码打个断点，遇到的方法如果是手写的，就"step into"，如果是依赖包里的，就"step over"，完整过一遍就理解了

‘’‘
ClassFactory.loadClass(packageName);
’‘’

ps.一定要配合Guide哥的专栏一起看
