### ISSUE TITLE
自动装配问题

### ISSUE THREAD

**Issue by liuxiany** [Snailclimb/jsoncat#3]
注入到容器的时候，用的类的名字或者，component的value值。自动装配的时候，只用类的名字去get而没用用component的value值。如果一个bean，用component注解注入容器，但是用的别名，别名和类名不一样，就get不出来了。

**Comment by Snailclimb** [comment]
> 注入到容器的时候，用的类的名字或者，component的value值。自动装配的时候，只用类的名字去get而没用用component的value值。如果一个bean，用component注解注入容器，但是用的别名，别名和类名不一样，就get不出来了。

对的！一个小Bug，感谢老哥提醒！
